- name: configure db server
  hosts: db
  become: yes
  vars:
    login_user: root
    login_host: 172.31.21.81

  vars_prompt:
  - name: PASSOWRD
    prompt: please enter passowrd
    private: false
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  
  - name: restart and enable server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install mysql dependencies
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography   
      executable: pip3.9

  - name: check my db connection
    community.mysql.mysql_info:
      login_user: "{{ login_user }}"
      login_password: "{{ PASSOWRD }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: true
    register: mysql_connection_info

  - name: check output error 
    ansible.builtin.debug:
      msg: "output is: {{ mysql_connection_info }}"

  - name: setup db password 
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{ PASSWORD }}
    when: mysql_connection_info.failed is true